[dependencies]
base = "0.11.3"

[package]
name = "dao-proposal-engine"
version = "0.1.0"
description = "A library for creating, voting on and executing proposals"
repository = "https://github.com/edjcase/motoko_proposal_engine"
keywords = [ "dao", "proposal", "proposals", "vote", "voting" ]
license = "MIT"

[dev-dependencies]
test = "1.0.1"